name: env6
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - expat=2.7.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=15.1.0
  - libhwloc=2.12.1
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libopenblas=0.3.29
  - libsqlite=3.45.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libta-lib=0.4.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - ncurses=6.4.20240210
  - openssl=3.6.0
  - pip=25.1.1
  - pthread-stubs=0.3
  - python=3.10.18
  - python_abi=3.10
  - readline=8.2
  - sqlite=3.45.3
  - ta-lib=0.5.1
  - tbb=2021.13.0
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - aiodns==3.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiosignal==1.4.0
      - alembic==1.17.2
      - anchorpy==0.21.0
      - anchorpy-core==0.2.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.10.0
      - apscheduler==3.11.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - based58==0.1.1
      - binance-bulk-downloader==1.1.0.1
      - bitarray==3.6.1
      - borsh-construct==0.1.0
      - bottle==0.13.4
      - cachecontrol==0.14.4
      - cachetools==6.2.4
      - catboost==1.2.8
      - certifi==2025.10.5
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - ckzg==2.1.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - construct==2.10.68
      - construct-typing==0.5.6
      - contourpy==1.3.2
      - cryptography==45.0.6
      - curl-cffi==0.13.0
      - cycler==0.12.1
      - cytoolz==1.0.1
      - distro==1.9.0
      - dm-tree==0.1.9
      - einops==0.8.1
      - eth-abi==5.2.0
      - eth-account==0.13.7
      - eth-hash==0.7.1
      - eth-keyfile==0.8.1
      - eth-keys==0.7.0
      - eth-rlp==2.2.0
      - eth-typing==5.2.1
      - eth-utils==5.3.0
      - eval-type-backport==0.3.0
      - exceptiongroup==1.3.0
      - fastapi==0.124.4
      - feedparser==6.0.11
      - filelock==3.20.0
      - firebase-admin==7.1.0
      - flatbuffers==25.9.23
      - fonttools==4.59.0
      - frozendict==2.4.7
      - frozenlist==1.7.0
      - fsspec==2025.10.0
      - gast==0.6.0
      - google-api-core==2.28.1
      - google-auth==2.45.0
      - google-cloud-core==2.5.0
      - google-cloud-firestore==2.22.0
      - google-cloud-storage==3.7.0
      - google-crc32c==1.8.0
      - google-pasta==0.2.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - graphviz==0.21
      - greenlet==3.2.4
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h11==0.16.0
      - h2==4.3.0
      - h5py==3.15.1
      - hexbytes==1.3.1
      - hf-xet==1.2.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - hyperframe==6.1.0
      - hyperliquid==0.4.66
      - hyperliquid-python-sdk==0.18.0
      - idna==3.11
      - iniconfig==2.3.0
      - investpy==1.0.8
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - kditransform==1.2.0
      - keras==3.12.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - loguru==0.7.3
      - lxml==6.0.0
      - mako==1.3.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mplfinance==0.12.10b0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.4
      - multitasking==0.0.12
      - namex==0.1.0
      - narwhals==2.2.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==1.100.2
      - opt-einsum==3.4.0
      - optree==0.17.0
      - optuna==4.6.0
      - optuna-dashboard==0.20.0
      - packaging==25.0
      - parsimonious==0.10.0
      - peewee==3.18.3
      - pillow==11.3.0
      - plotly==6.3.0
      - pluggy==1.6.0
      - posthog==6.9.3
      - propcache==0.3.2
      - proto-plus==1.27.0
      - protobuf==4.25.8
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybit==5.11.0
      - pycares==4.10.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.12.0
      - pygments==2.19.2
      - pyheck==0.1.5
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - pytest==9.0.2
      - python-decouple==3.8
      - python-telegram-bot==22.3
      - regex==2025.7.34
      - requests==2.32.5
      - retry==0.9.2
      - rich==14.2.0
      - rlp==4.1.0
      - rsa==4.9.1
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - setuptools==80.9.0
      - sgmllib3k==1.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - solana==0.36.6
      - solders==0.26.0
      - sqlalchemy==2.0.44
      - starlette==0.50.0
      - sumtypes==0.1a6
      - sympy==1.14.0
      - tabpfn==6.0.6
      - tabpfn-common-utils==0.2.10
      - tabulate==0.9.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-probability==0.24.0
      - termcolor==3.2.0
      - tf-keras==2.17.0
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tomli==2.3.0
      - toolz==0.11.2
      - torch==2.9.1
      - triton==3.5.1
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - tzlocal==5.3.1
      - unicorn==2.1.4
      - unidecode==1.4.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websockets==15.0
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - yarl==1.20.1
      - yfinance==1.0

